### ISSUE TITLE
browser back (and forward) change url but not page

### ISSUE THREAD

**Issue by babycourageous** [AlexxNB/svelte-docs#10]
Hi there!

I'm looking at the project and noticed on the official docs site as well as if you run it locally the browser back and forward only change the url in the browser address bar but do not update the page.

You have to refresh in order to update it.

I'm excited to possibly use this for some documentation. Thanks for making it available!

**Comment by AlexxNB** [comment]
Yeah. It is bug. I'll fix this ASAP.

**Comment by AlexxNB** [comment]
fixed in  `@svelte-docs/core@0.10.1`. Please update.

**Comment by babycourageous** [comment]
Thanks for the quick update @AlexxNB !
