### ISSUE TITLE
[build]: cannot read property 'code' of undefined

### ISSUE THREAD

**Issue by BenoitPingris** [AlexxNB/svelte-docs#11]
Hey,

Thank you for this project, it's really easy to use !

But unfortunately, I have an error when I'm trying to build:

```bash
$ npm run build 

> svelte-docs-template@0.3.1 build /home/benoitp/Work/perso/svmilli/docs_src
> rollup -c node_modules/@svelte-docs/core/rollup.config.js


/home/benoitp/Work/perso/svmilli/docs_src/node_modules/@svelte-docs/core/main.js → __DOCS__/dist/bundle.js...
(!) A plugin is directly adding properties to the bundle object in the "generateBundle" hook. This is deprecated and will be removed in a future Rollup version, please use "this.emitFile" instead.
[!] (plugin rollup_plugin_fixident) TypeError: Cannot read property 'code' of undefined
TypeError: Cannot read property 'code' of undefined
    at Object.writeBundle (/home/benoitp/Work/perso/svmilli/docs_src/node_modules/@svelte-docs/core/rollup.config.js:247:63)
    at /home/benoitp/Work/perso/svmilli/docs_src/node_modules/rollup/dist/shared/rollup.js:18223:25
    at async Promise.all (index 0)
    at /home/benoitp/Work/perso/svmilli/docs_src/node_modules/rollup/dist/shared/rollup.js:18877:17
    at async Promise.all (index 0)
    at build (/home/benoitp/Work/perso/svmilli/docs_src/node_modules/rollup/dist/bin/rollup:1466:5)
    at runRollup (/home/benoitp/Work/perso/svmilli/docs_src/node_modules/rollup/dist/bin/rollup:1610:21)
```

I have updated some dependencies after I `npm init svelte-docs`, otherwise I couldn't run the docs.
So here my updated package:
```json
{
  "dependencies": {
    "@svelte-docs/server": "^0.1.3",
    "milligram": "^1.3.0"
  },
  "devDependencies": {
    "@svelte-docs/core": "^0.10.1",
    "@svelte-docs/publisher": "^0.2.3",
    "@svelte-docs/themes": "^1.0.0",
    "npm-run-all": "^4.1.5",
    "rollup": "^2.10.0",
    "svelte": "^3.22.2"
  },
}
```

I try to look a bit around with the error logs I have no clue what's going on !

Thanks for the help

**Comment by AlexxNB** [comment]
You should rollback Rollup to version 1.*. There are some changes in v.2, which are not compitable with plugins in `@svelte-docs/core`. I'll fix this issue in the future.

**Comment by AlexxNB** [comment]
And you can remove from the `package.json`:
```
 "rollup": "^2.10.0",
 "svelte": "^3.22.2"
```

In new template version I removed this lines, there are not necessary.

**Comment by BenoitPingris** [comment]
Ok nice ! I just deleted these 2 lines and it works !

By the way how the deployment works ? I tried `npm run deploy` and it didnt work:
```sh
Publishing the documentation...
(node:259506) UnhandledPromiseRejectionWarning: Error: Branch ("master") definition does not exist in the config.
```
I also tried to do the same on `gh-pages` branch but I had the same issue

**Comment by AlexxNB** [comment]
did you run it inside initialized GIT repository?

**Comment by BenoitPingris** [comment]
Yes I did, I have this structure:
```bash
.
├── .git
├── docs_src
│   ├── __DOCS__
│   ├── package.json
│   ├── package-lock.json
│   ├── src
│   └── svelte-docs.config.js
├── package.json
├── package-lock.json
├── README.md
├── rollup.config.js
└── src
    ├── Button.svelte
    ├── Card.svelte
    ├── Col.svelte
    ├── Container.svelte
    ├── index.js
    ├── Input.svelte
    ├── Modal.svelte
    ├── Quote.svelte
    ├── Row.svelte
    ├── Table.svelte
    └── utils.js
```

**Comment by BenoitPingris** [comment]
Or did you mean that the docs should be in their own git repo ?

**Comment by AlexxNB** [comment]
Yes, it is OK. 
Just test deploy on brand new repository with *doc_src* inside, created by `npm init docs-svelte`  - it's work.
Then, I tried to deploy [your repo](https://github.com/BenoitPingris/svmilli) - and  also seems ok(till auth request).
So I can't reproduce this.

**Comment by BenoitPingris** [comment]
Haha wtf why it does not work with me ?
I'm on linux so maybe that's an issue ?

**Comment by AlexxNB** [comment]
I use Linux too.
Please commit your actual version, I'll try to fork it and test again.

**Comment by BenoitPingris** [comment]
Ok ! 
Nice finally everything seems to work well, the documentation seems to have been pushed to gh-pages and published (still 404 on github but that's ok).

Thank you for your help ~

**Comment by AlexxNB** [comment]
Nice! 
Thanks, will fix the typo. Anyway, they have redirect from `com` to `io`.

**Comment by BenoitPingris** [comment]
Oh not in my case :smile: I still have 404 if I go on .com, maybe it has to take some time before it setup the redirection I don't know
