### ISSUE TITLE
Missing id in headings

### ISSUE THREAD

**Issue by shirotech** [AlexxNB/svelte-docs#14]
`# Heading 1` `## Heading 2` `### Heading 3` etc. are not assigning id attribute even if we follow the standard for custom ids. e.g. `### Heading {#heading}` id is still missing. This is so we can deep-link to it from a table of contents for example.

**Comment by shirotech** [comment]
Also a separate but related issue, the `properties` block won't let us create a link in the description section.

e.g.

```
```properties
`heading` | some heading, refer [this section](#heading) for more info | dev
```
```

But what we get is just html, and not a rendered link.

Sorry for being a pain, have only used this tool for a few hours and I really like it! Just wanted to help by reporting issues as I find it, hope it is helpful.

**Comment by AlexxNB** [comment]
update to `@svelte-docs/core":@0.10.2` and `@svelte-docs/themes@1.0.1`

**Comment by babycourageous** [comment]
@AlexxNB Sorry to ping this issue but I'm noticing that when writing an internal link as in the example @shirotech provides (by using an `id`) the link is relative to the root localhost url (i.e. localhost:5000/#heading) not the page you wrote the link on (i.e. localhost:5000/component/button#heading).

The same holds true if using this id-linking technique in the document or in the properties table.

Thanks!

**Comment by shirotech** [comment]
@babycourageous The hash should be relative to the page, that's how it should behave on the browser, but you're right it seems the Router is not picking that up.

It's not an issue for me because I am overriding the behaviour with some hacks in `topbar.md` as I don't really want it to route, but rather just scroll to a particular section. Hope this helps.

```vue
<script context="module">
  document.addEventListener('click', (e) => {
    const el = e.target;

    if (el.nodeName === 'A') {
      const href = el.getAttribute('href');

      if (href && href.startsWith('#')) {
        scrollToHash(e, href);
      }
    }
  });

  function scrollToHash(event, hash = window.location.hash) {
    if (hash) {
      const target = document.getElementById(hash.substr(1));

      if (target) {
        if (event) {
          event.preventDefault();
          event.stopPropagation();
        }

        scrollTo({top: target.offsetTop - 60, behavior: 'smooth'});
      }
    }
  }

  setTimeout(scrollToHash);
</script>
```

**Comment by babycourageous** [comment]
@shirotech 
Yeah - I don't need it to scroll to it but might need to borrow some of that hack to make some adjustments so it will link to the id on the page somehow.

Thanks!
