### ISSUE TITLE
script context="module" throws off properties builtin

### ISSUE THREAD

**Issue by babycourageous** [AlexxNB/svelte-docs#21]
Hi there

It appears that having a `<script context="module">` alongside the regular `<script>` tag throws off the `properties` builtin when autogenerating properties. I have a `<script context="module">` in a component that exports component level constants (not meant for user consumption). Because of this svelte docs  autogenerates based on the `context="module"` tag instead of the regular `script` tag.

I gather this means in these cases we should use the markdown table approach instead of autogenerating?

Just wanted to let you know of this behavior.

Thanks!

**Comment by shirotech** [comment]
I had the same problem, moving the script tag with the context below the main script works, no side effects as a result.

But would be good if we can tweak the regex to ignore the script tag with context.

**Comment by babycourageous** [comment]
Thanks @shirotech. Figured that might be the case.

**Comment by babycourageous** [comment]
Thanks again @AlexxNB for another speedy fix!

I am loving this project and all the work you put into it!

**Comment by AlexxNB** [comment]
The gratitude goes to @shirotech =)

**Comment by babycourageous** [comment]
Then many thanks to both you and @shirotech !
