### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by Thebigbignooby** [AlexxNB/svelte-docs#7]
Hey, kudos for this library, looks good 👍 

would be awesome if you could include a built-in dark mode and theme switcher.

I would do it but I don't have the time right now :/

**Comment by AlexxNB** [comment]
Thanks a lot!  
Yah, the time is a thing which I have no too =)
As I think, darkmode may be added easy in the [current two themes](https://github.com/AlexxNB/svelte-docs/tree/master/packages/themes). They both use custom properties for theming, so we need just implement a switcher.
